### ISSUE TITLE
Seems like the MHZ16 firmware can monopolize Arduino resources

### ISSUE THREAD

**Issue by wsnook** [OpenAgInitiative/openag_mhz16#5]
This might be nothing, but it looks like the MHZ16 firmware could be monopolizing processor and I2C bus time on the PFC2's Arduino--at least when it has a sensor communication problem. If that's happening, it might be degrading firmware performance for all of the sensors and actuators.

Tonight, I found that the majority of the messages getting sent from my Mega2560's I2C master are trying to poll the MHZ16 (address 77). By majority, I mean that when I captured 1524 I2C messages over several seconds:
- 1497 were for address 77 (MHZ16)
- 12 were for address 92 (am2315)
- 8 were for address 99 (Atlas pH)
- 7 were for address 100 (Atlas EC)

It seems weird to have two orders of magnitude more I2C bus activity for the CO2 sensor compared to EC, pH, temperature, and humidity all added together.

It's possible that I'm just seeing this because I don't have sensors connected, but, if so, my experience could be relevant to CO2 sensor failure on a full PFC2. I'm running a recent checkout of openag_brain from a couple days ago with Arduino firmware for the [default](https://github.com/OpenAgInitiative/openag_brain/blob/master/fixtures/default.json) and  [personal_food_computer_v2](https://github.com/OpenAgInitiative/openag_brain/blob/master/fixtures/personal_food_computer_v2.json) fixtures loaded, but I don't have any sensors connected.

This is my hardware setup:

![image1](https://cloud.githubusercontent.com/assets/1828676/22615424/32df3356-ea5a-11e6-9f5e-d2233a5b0ffe.JPG)

For context about why I was monitoring the I2C bus, I'm working on a scheme to help aspiring OpenAg developers get started on UI or openag_brain development without having to spend a ton of money on hardware. I figure that a $12 Uno clone bit-banging I2C might be able to fake the PFC2 Mega into thinking it was talking to hundreds of dollars worth of sensors. For now I'm just working on a software I2C protocol tracer on my Uno.

Here's a screenshot of my [protocol tracer](https://github.com/wsnook/sim-indoor-farm/tree/master/pfc2_uno) with some of the results I referred to above:

![decode 2](https://cloud.githubusercontent.com/assets/1828676/22615434/70296916-ea5a-11e6-99a1-d7ce3482205a.png)

/cc @LeonChambers @gordonbrander

**Comment by wsnook** [comment]
This is related to https://github.com/OpenAgInitiative/openag_python/issues/23 (profiling firmware)

**Comment by wsnook** [comment]
I've been improving my I2C monitor and looking at this more. It seems like the I2C activity repeats on a 2 second cycle:
1. One second of steady activity with about 5082 messages in a row for the MHZ16.
2. One second of mostly idle time mixed in with 13 messages split between Atlas PH, Atlas EC, MHZ16, and the AM2315

**Comment by wsnook** [comment]
I think this may be happening because `_time_of_last_reading` [gets initialized](https://github.com/OpenAgInitiative/openag_mhz16/blob/7272cae98ad315f11217c509a86e5cc435c7e79f/openag_mhz16.cpp#L8) to `0` and [openag_mhz16.cpp#L71-L79](https://github.com/OpenAgInitiative/openag_mhz16/blob/7272cae98ad315f11217c509a86e5cc435c7e79f/openag_mhz16.cpp#L71-L79) only runs `_time_of_last_reading = millis();` when `_sensor.measure()` is successful:
```
if (curr_time - _time_of_last_reading > _min_update_interval) {
    if (_sensor.measure()) {
      if (status_level == OK) {
        _send_air_carbon_dioxide = true;
        _time_of_last_reading = millis();
      }
      else {
        begin();
      }
```

So, if there's a communication problem with the CO2 sensor, `curr_time - _time_of_last_reading > _min_update_interval` will simplify to `curr_time > _min_update_interval`, which will usually be true. So, `_sensor.measure()` will get called almost every time that `MHZ16::update()` gets called.

For other sensors, the firmware keeps track of the last time it attempted to talk to the sensor rather than the last time it successfully received a response:

- [openag_atlas_ph.cpp#L63-L64](https://github.com/OpenAgInitiative/openag_atlas_ph/blob/a98a09f697f8af42bc8dc00dde709d55e5cd9176/openag_atlas_ph.cpp#L63-L64)
    ```
    void AtlasPh::send_query() {
      _time_of_last_query = millis();
    ```

- [openag_am2315.cpp#L34-L39](https://github.com/OpenAgInitiative/openag_am2315/blob/5c5550ad5b74fcd983782a4e4dd689f4679282e5/openag_am2315.cpp#L34-L39)
    ```
    void Am2315::update() {
      if (millis() - _time_of_last_reading > _min_update_interval) {
          readData();
          _time_of_last_reading = millis();
      }
    }
    ```

**Comment by LeonChambers** [comment]
Nice investigative work. Seems like this could be fixed with a pretty trivial code change. Feel free to open a PR with the fix.

**Comment by wsnook** [comment]
Okay, I'll do that. I don't have a real CO2 sensor to test against though, so I'll need somebody to test it on real hardware.

**Comment by wsnook** [comment]
Pull request: https://github.com/OpenAgInitiative/openag_mhz16/pull/6
